import {
  SalonType,
  SelectOptionType,
  PriceRangeValuesEnum,
} from 'types';

export const PRICE_OPTIONS: SelectOptionType[] = [
  {
    value: PriceRangeValuesEnum.ALL,
    label: 'All Salons',
  },
  {
    value: PriceRangeValuesEnum.RANGE_1,
    label: 'Pris 0 - 250 kr',
  },
  {
    value: PriceRangeValuesEnum.RANGE_2,
    label: 'Pris 250 - 500 kr',
  },
  {
    value: PriceRangeValuesEnum.RANGE_3,
    label: 'Pris 500 - 750 kr',
  },
];

export const SALONS_LIST: SalonType[] = [
  {
    id: 'salon-1',
    companyName: 'Sax & Fön',
    price: 320,
    reviews: 32,
    street: 'Vidargatan 25',
    distance: 30,
    openTime: '12.00',
    stars: 3,
    city: 'Kiruna',
    postCode: '113 57',
  },
  {
    id: 'salon-2',
    companyName: 'Hårizont',
    price: 410,
    reviews: 32,
    street: 'Upplandsgatan 39',
    distance: 30,
    openTime: '12.00',
    stars: 5,
    city: 'Stockholm',
    postCode: '113 54',
  },
  {
    id: 'salon-3',
    companyName: 'Hårhuset',
    price: 260,
    reviews: 32,
    street: 'Rådmansgatan 4',
    distance: 30,
    openTime: '12.00',
    stars: 2,
    city: 'Stockholm',
    postCode: '113 21',
  },
  {
    id: 'salon-4',
    companyName: 'Hair & Nu',
    price: 340,
    reviews: 18,
    street: 'Frejgatan 5',
    distance: 30,
    openTime: '12.00',
    stars: 3,
    city: 'Stockholm',
    postCode: '113 01',
  },
  {
    id: 'salon-5',
    companyName: 'Harley Davidson',
    price: 115,
    reviews: 32,
    street: 'Odengatan 94',
    distance: 30,
    openTime: '12.00',
    stars: 5,
    city: 'Göteborg',
    postCode: '112 99',
  },
  {
    id: 'salon-6',
    companyName: 'Combs & Scisors',
    price: 90,
    reviews: 29,
    street: 'Ystadgatan 9',
    distance: 10,
    openTime: '7.00',
    stars: 4,
    city: 'Göteborg',
    postCode: '112 47',
  },
  {
    id: 'salon-7',
    companyName: 'Fred Durst',
    price: 220,
    reviews: 38,
    street: 'Lundgatan 55',
    distance: 10,
    openTime: '7.00',
    stars: 1,
    city: 'Linköping',
    postCode: '114 12',
  },
  {
    id: 'salon-8',
    companyName: 'Bonnie & Clyde',
    price: 590,
    reviews: 43,
    street: 'Uppsalagatan 56',
    distance: 10,
    openTime: '5.00',
    stars: 5,
    city: 'Göteborg',
    postCode: '113 68',
  },
];

export enum SalonTextEnum {
  SALON_INFO = `Lorem ipsum dolor sit amet, vulputate nunc. Auctor viverra.
  Ridiculus feugiat nunc porttitor volut pat, acu quis torquent
  iaculis ultricies massa, duis nun quis que amet.`,
  SCHEMA = 'Schema Content',
}
